const CLUE_LISTS = {
  animals: [
    'striped', 'spotted', 'furry', 'feathered', 'scaly', 'slimy', 'spiny', 'fluffy',
    'hairy', 'bald', 'wrinkled', 'sleek', 'muscular', 'plump', 'lean', 'bulky',
    'tiny', 'massive', 'enormous', 'miniature', 'long', 'stubby', 'tall', 'squat',
    'horned', 'tusked', 'fanged', 'clawed', 'webbed', 'winged', 'finned', 'tailed',
    'armored', 'shelled', 'hoofed', 'pouched', 'beaked', 'whiskered', 'maned', 'crested',
    'black', 'white', 'brown', 'golden', 'orange', 'red', 'blue', 'green',
    'gray', 'silver', 'pink', 'yellow', 'purple', 'tan', 'cream', 'copper',
    'camouflaged', 'patterned', 'multicolored', 'iridescent', 'translucent', 'pale', 'vivid', 'dark',
    'aggressive', 'docile', 'timid', 'curious', 'playful', 'lazy', 'alert', 'cunning',
    'loyal', 'territorial', 'social', 'solitary', 'migratory', 'nomadic', 'patient', 'restless',
    'fierce', 'gentle', 'stubborn', 'obedient', 'mischievous', 'cautious', 'bold', 'shy',
    'intelligent', 'clever', 'trainable', 'wild', 'tame', 'feral', 'skittish', 'calm',
    'fast', 'slow', 'graceful', 'clumsy', 'agile', 'sluggish', 'swift', 'lumbering',
    'slithering', 'galloping', 'soaring', 'diving', 'burrowing', 'climbing', 'leaping', 'crawling',
    'gliding', 'hovering', 'waddling', 'prancing', 'prowling', 'stalking', 'charging', 'darting',
    'swimming', 'floating', 'pouncing', 'scurrying', 'trotting', 'sprinting', 'creeping', 'swooping',
    'roaring', 'growling', 'hissing', 'chirping', 'howling', 'barking', 'purring', 'squeaking',
    'trumpeting', 'croaking', 'buzzing', 'clicking', 'chattering', 'screeching', 'cooing', 'bellowing',
    'whistling', 'snorting', 'grunting', 'snarling', 'whimpering', 'yelping', 'cackling', 'trilling',
    'tropical', 'arctic', 'desert', 'forest', 'mountain', 'ocean', 'freshwater', 'swamp',
    'underground', 'treetop', 'coastal', 'grassland', 'tundra', 'jungle', 'cave', 'reef',
    'suburban', 'urban', 'rural', 'island', 'volcanic', 'polar', 'wetland', 'savanna',
    'nocturnal', 'diurnal', 'burrowed', 'nesting', 'denning', 'perched', 'submerged', 'roaming',
    'carnivorous', 'herbivorous', 'omnivorous', 'predatory', 'scavenging', 'grazing', 'hunting', 'foraging',
    'venomous', 'poisonous', 'parasitic', 'filter-feeding', 'pecking', 'gnawing', 'ambushing', 'trapping',
    'endangered', 'extinct', 'common', 'rare', 'ancient', 'prehistoric', 'evolved', 'adapted',
    'domesticated', 'exotic', 'native', 'invasive', 'seasonal', 'hibernating', 'molting', 'shedding',
    'egg-laying', 'live-bearing', 'metamorphic', 'larval', 'juvenile', 'mature', 'newborn', 'aging',
    'thick-skinned', 'thin-skinned', 'long-necked', 'short-legged', 'big-eyed', 'sharp-toothed', 'flat-faced', 'long-tailed',
    'broad-winged', 'deep-voiced', 'narrow-snouted', 'wide-mouthed', 'hollow-boned', 'warm-blooded', 'cold-blooded', 'double-jointed',
    'pack', 'herd', 'flock', 'swarm', 'colony', 'pride', 'school', 'pod',
    'paired', 'lone', 'alpha', 'maternal', 'paternal', 'communal', 'cooperative', 'competitive',
    'camouflaging', 'mimicking', 'stinging', 'biting', 'scratching', 'kicking', 'ramming', 'fleeing',
    'hiding', 'bluffing', 'inflating', 'spraying', 'regenerating', 'playing-dead', 'coiling', 'rattling',
    'predator', 'prey', 'hunter', 'scavenger', 'parasite', 'companion', 'pest', 'guardian',
    'migrant', 'drifter', 'forager', 'grazer', 'browser', 'ambusher', 'tracker', 'sentinel',
    'swimmer', 'flyer', 'runner', 'climber', 'digger', 'diver', 'jumper', 'crawler',
    'bottom-dweller', 'treetop-dweller', 'burrower', 'nester', 'wanderer', 'hermit', 'survivor', 'recluse',
    'mud', 'sand', 'coral', 'kelp', 'grass', 'bark', 'ice', 'snow',
    'rock', 'den', 'nest', 'burrow', 'hive', 'web', 'shell', 'cocoon',
    'branch', 'canopy', 'undergrowth', 'riverbed', 'shoreline', 'tide', 'current', 'depth',
    'majestic', 'fearsome', 'adorable', 'ugly', 'beautiful', 'grotesque', 'elegant', 'awkward',
    'harmless', 'dangerous', 'deadly', 'ferocious', 'menacing', 'cuddly', 'prickly', 'bristly',
    'stealthy', 'noisy', 'silent', 'loud', 'quiet', 'smelly', 'clean', 'dirty',
    'wet', 'dry', 'warm', 'cold', 'rough', 'smooth', 'soft', 'hard',
    'flexible', 'rigid', 'fragile', 'tough', 'resilient', 'delicate', 'robust', 'sturdy',
    'heavy', 'lightweight', 'buoyant', 'dense', 'hollow', 'solid', 'transparent', 'opaque',
    'colorful', 'drab', 'bright', 'dull', 'shimmering', 'matte', 'glossy', 'textured',
    'symmetrical', 'lopsided', 'streamlined', 'aerodynamic', 'compact', 'sprawling', 'coiled', 'stretched',
    'fanlike', 'tubular', 'spherical', 'flat', 'curved', 'angular', 'segmented', 'jointed',
    'sedentary', 'amphibious', 'aquatic', 'terrestrial', 'arboreal', 'aerial', 'marine', 'riparian',
    'toxic', 'electric', 'magnetic', 'luminous', 'echolocating', 'infrared', 'ultrasonic', 'bioluminescent',
    'symbiotic', 'mutualistic', 'commensal', 'apex', 'keystone', 'indicator', 'flagship', 'endemic',
    'wiry', 'stocky', 'lanky', 'gangly', 'portly', 'gaunt', 'rotund', 'spindly',
    'webfooted', 'flat-footed', 'sure-footed', 'nimble', 'ponderous', 'lithe', 'supple', 'stiff',
    'ravenous', 'satiated', 'thirsty', 'bloated', 'famished', 'gorging', 'fasting', 'feasting',
    'crepuscular', 'digging', 'preening', 'grooming', 'sunbathing', 'wobbly', 'leggy', 'squid-like',
    'eel-like', 'moth-like', 'worm-like', 'crab-like', 'frog-like', 'tadpole', 'chrysalis', 'pupa',
    'hatchling', 'yearling', 'fledgling', 'pigmented', 'albino', 'melanistic', 'leucistic', 'mottled',
    'banded', 'ringed', 'barn', 'meadow', 'prairie', 'canyon', 'delta', 'estuary',
    'lagoon', 'atoll', 'claw', 'talon', 'antler', 'tusk', 'horn', 'fang',
    'gill', 'tentacle', 'migrating', 'spawning', 'mating', 'courting', 'brooding', 'nursing',
    'weaning', 'fleet', 'plodding', 'bounding',
  ],

  food: [
    'sweet', 'sour', 'salty', 'bitter', 'savory', 'umami', 'tangy', 'tart',
    'spicy', 'mild', 'bland', 'rich', 'sharp', 'pungent', 'zesty', 'mellow',
    'smoky', 'earthy', 'nutty', 'fruity', 'floral', 'herbal', 'minty', 'peppery',
    'garlicky', 'buttery', 'cheesy', 'vinegary', 'briny', 'citrusy', 'chocolatey', 'caramelized',
    'honeyed', 'sugary', 'syrupy', 'bittersweet', 'acidic', 'alkaline', 'metallic', 'astringent',
    'woody', 'musky', 'toasty', 'roasty', 'malty', 'yeasty', 'funky', 'grassy',
    'licorice', 'vanilla', 'cinnamon', 'lemony', 'coconutty', 'maple', 'truffle', 'smokey',
    'crispy', 'crunchy', 'chewy', 'tender', 'flaky', 'crumbly', 'smooth', 'creamy',
    'gooey', 'sticky', 'silky', 'velvety', 'grainy', 'gritty', 'lumpy', 'mushy',
    'fluffy', 'dense', 'airy', 'foamy', 'bubbly', 'fizzy', 'gelatinous', 'rubbery',
    'brittle', 'snappy', 'firm', 'soft', 'hard', 'moist', 'dry', 'crackly',
    'juicy', 'succulent', 'stringy', 'fibrous', 'pulpy', 'mealy', 'waxy', 'oily',
    'springy', 'spongy', 'doughy', 'pasty', 'powdery', 'granular', 'chunky', 'hot',
    'cold', 'warm', 'chilled', 'frozen', 'steaming', 'lukewarm', 'icy', 'room-temperature',
    'scalding', 'tepid', 'bubbling', 'simmering', 'boiling', 'melted', 'solidified', 'refrigerated',
    'thawed', 'cooled', 'heated', 'toasted', 'charred', 'burnt', 'raw', 'fried',
    'baked', 'grilled', 'roasted', 'steamed', 'boiled', 'sauteed', 'braised', 'poached',
    'broiled', 'smoked', 'cured', 'pickled', 'fermented', 'dried', 'dehydrated', 'blanched',
    'seared', 'blackened', 'glazed', 'marinated', 'seasoned', 'brined', 'infused', 'stuffed',
    'wrapped', 'layered', 'stacked', 'rolled', 'folded', 'sliced', 'diced', 'chopped',
    'minced', 'shredded', 'grated', 'pureed', 'mashed', 'blended', 'whisked', 'kneaded',
    'proofed', 'risen', 'flattened', 'pressed', 'strained', 'filtered', 'reduced', 'candied',
    'torched', 'flambeed', 'deep-fried', 'stir-fried', 'pan-fried', 'air-fried', 'golden', 'brown',
    'white', 'red', 'green', 'yellow', 'orange', 'purple', 'colorful', 'pale',
    'vibrant', 'dark', 'translucent', 'opaque', 'clear', 'cloudy', 'glossy', 'matte',
    'shiny', 'dull', 'speckled', 'striped', 'swirled', 'marbled', 'round', 'flat',
    'tall', 'thin', 'thick', 'long', 'square', 'triangular', 'spiral', 'twisted',
    'braided', 'latticed', 'hollowed', 'filled', 'topped', 'coated', 'dusted', 'drizzled',
    'frosted', 'crusted', 'spotted', 'Italian', 'Mexican', 'Japanese', 'Chinese', 'Indian',
    'French', 'Thai', 'Greek', 'Korean', 'Vietnamese', 'American', 'Brazilian', 'Moroccan',
    'Ethiopian', 'Turkish', 'Spanish', 'Caribbean', 'Persian', 'German', 'British', 'Hawaiian',
    'Cajun', 'Mediterranean', 'Nordic', 'Peruvian', 'Lebanese', 'Indonesian', 'Filipino', 'Jamaican',
    'Cuban', 'Polish', 'Russian', 'breakfast', 'lunch', 'dinner', 'snack', 'appetizer',
    'entree', 'dessert', 'side', 'brunch', 'midnight', 'holiday', 'festive', 'comfort',
    'street', 'gourmet', 'homemade', 'restaurant', 'takeout', 'buffet', 'potluck', 'picnic',
    'barbecue', 'banquet', 'wedding', 'organic', 'fresh', 'canned', 'instant', 'processed',
    'homegrown', 'imported', 'seasonal', 'vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'kosher',
    'halal', 'keto', 'paleo', 'low-fat', 'sugar-free', 'whole-grain', 'fortified', 'natural',
    'artificial', 'preserved', 'local', 'flour', 'sugar', 'butter', 'egg', 'milk',
    'cream', 'oil', 'vinegar', 'yeast', 'baking', 'dough', 'batter', 'crust',
    'frosting', 'glaze', 'icing', 'sauce', 'broth', 'stock', 'gravy', 'marinade',
    'dressing', 'condiment', 'garnish', 'herb', 'spice', 'seasoning', 'salt', 'pepper',
    'garlic', 'onion', 'ginger', 'cheese', 'bread', 'rice', 'pasta', 'noodle',
    'grain', 'bean', 'lentil', 'delicious', 'disgusting', 'tasty', 'flavorful', 'appetizing',
    'revolting', 'mouthwatering', 'unappetizing', 'heavenly', 'divine', 'satisfying', 'filling', 'light',
    'heavy', 'refreshing', 'nourishing', 'indulgent', 'decadent', 'simple', 'complex', 'elaborate',
    'rustic', 'elegant', 'humble', 'authentic', 'traditional', 'modern', 'fusion', 'experimental',
    'classic', 'innovative', 'trendy', 'cheap', 'expensive', 'affordable', 'luxurious', 'generous',
    'tiny', 'oversized', 'miniature', 'aromatic', 'fragrant', 'stinky', 'odorless', 'subtle',
    'overpowering', 'balanced', 'intense', 'chewing', 'swallowing', 'sipping', 'gulping', 'nibbling',
    'devouring', 'tasting', 'sampling', 'cooking', 'preparing', 'serving', 'plating', 'garnishing',
    'drizzling', 'sprinkling', 'pouring', 'peeling', 'coring', 'seeding', 'trimming', 'carving',
    'portioning', 'measuring', 'mixing', 'fermenting', 'canning', 'jarring', 'bottling', 'aging',
    'ripening', 'wilting', 'browning', 'oven', 'stove', 'grill', 'pan', 'pot',
    'skillet', 'wok', 'griddle', 'knife', 'fork', 'spoon', 'plate', 'bowl',
    'cup', 'glass', 'napkin', 'apron', 'timer', 'thermometer', 'scale', 'sieve',
    'colander', 'ladle', 'tongs', 'whisk', 'spatula', 'peeler', 'grater', 'blender',
    'mortar', 'rolling-pin', 'chopsticks', 'soupy', 'watery', 'concentrated', 'diluted', 'thickened',
    'crusty', 'pillowy', 'silken', 'coarse', 'refined', 'unprocessed', 'Argentinian', 'Nepalese',
    'Scottish', 'Taiwanese', 'Colombian', 'Nigerian', 'Icelandic', 'Portuguese', 'bite-sized', 'family-sized',
    'single-serving', 'shareable', 'finger-food', 'fork-friendly', 'spoonable', 'drinkable', 'orchard', 'garden-fresh',
    'vine-ripened', 'sun-dried', 'slow-cooked', 'flash-frozen', 'melt-in-mouth', 'al-dente', 'well-done', 'medium-rare',
    'sous-vide', 'spreadable', 'pourable', 'scoopable',
  ],

  places: [
    'peaceful', 'chaotic', 'eerie', 'lively', 'quiet', 'noisy', 'serene', 'bustling',
    'haunted', 'magical', 'mysterious', 'sacred', 'forbidden', 'welcoming', 'hostile', 'abandoned',
    'cozy', 'sterile', 'gloomy', 'cheerful', 'romantic', 'creepy', 'majestic', 'humble',
    'tranquil', 'turbulent', 'vibrant', 'somber', 'festive', 'solemn', 'wild', 'dignified',
    'tense', 'relaxed', 'oppressive', 'liberating', 'inspiring', 'depressing', 'enchanting', 'dreary',
    'inviting', 'foreboding', 'charming', 'bleak', 'idyllic', 'sinister', 'quaint', 'imposing',
    'vast', 'tiny', 'enormous', 'cramped', 'spacious', 'narrow', 'wide', 'towering',
    'sprawling', 'compact', 'endless', 'confined', 'expansive', 'intimate', 'massive', 'miniature',
    'deep', 'shallow', 'tall', 'low', 'broad', 'slender', 'thick', 'thin',
    'cavernous', 'claustrophobic', 'sweeping', 'petite', 'colossal', 'modest', 'grand', 'rocky',
    'sandy', 'muddy', 'grassy', 'paved', 'cobblestone', 'dirt', 'dusty', 'wet',
    'dry', 'frozen', 'flooded', 'cracked', 'smooth', 'rough', 'uneven', 'hilly',
    'flat', 'steep', 'sloping', 'terraced', 'layered', 'elevated', 'sunken', 'winding',
    'straight', 'curved', 'circular', 'angular', 'symmetrical', 'irregular', 'geometric', 'jagged',
    'craggy', 'eroded', 'sculpted', 'polished', 'ridged', 'grooved', 'rippled', 'tropical',
    'arctic', 'arid', 'humid', 'temperate', 'windy', 'rainy', 'sunny', 'foggy',
    'misty', 'snowy', 'icy', 'stormy', 'overcast', 'clear', 'hazy', 'hot',
    'cold', 'warm', 'cool', 'freezing', 'sweltering', 'mild', 'harsh', 'monsoon',
    'drought', 'seasonal', 'shifting', 'unpredictable', 'stable', 'volatile', 'balmy', 'ancient',
    'modern', 'medieval', 'futuristic', 'prehistoric', 'colonial', 'Victorian', 'contemporary', 'ruined',
    'pristine', 'crumbling', 'restored', 'decaying', 'renovated', 'dilapidated', 'gleaming', 'weathered',
    'worn', 'rusty', 'mossy', 'overgrown', 'barren', 'lush', 'verdant', 'new',
    'old', 'timeless', 'dated', 'aging', 'eternal', 'freshly-built', 'centuries-old', 'stone',
    'brick', 'wooden', 'concrete', 'glass', 'steel', 'marble', 'granite', 'thatched',
    'tiled', 'plastered', 'painted', 'carved', 'molded', 'forged', 'reinforced', 'fortified',
    'walled', 'fenced', 'gated', 'open', 'enclosed', 'roofed', 'adobe', 'bamboo',
    'sandstone', 'limestone', 'slate', 'copper', 'iron', 'timber', 'bright', 'dark',
    'dim', 'shadowy', 'sunlit', 'moonlit', 'candlelit', 'neon', 'glowing', 'flickering',
    'sparkling', 'dazzling', 'blinding', 'murky', 'luminous', 'radiant', 'transparent', 'opaque',
    'reflective', 'mirrored', 'tinted', 'colorful', 'monochrome', 'faded', 'torchlit', 'starlit',
    'fluorescent', 'backlit', 'spotlit', 'overlit', 'underlit', 'ambient', 'crowded', 'empty',
    'populated', 'deserted', 'packed', 'sparse', 'teeming', 'desolate', 'public', 'private',
    'restricted', 'accessible', 'exclusive', 'communal', 'shared', 'personal', 'commercial', 'residential',
    'industrial', 'agricultural', 'military', 'religious', 'educational', 'governmental', 'touristy', 'local',
    'international', 'multicultural', 'homogeneous', 'diverse', 'segregated', 'integrated', 'coastal', 'inland',
    'mountainous', 'subterranean', 'underwater', 'floating', 'valley', 'plateau', 'northern', 'southern',
    'eastern', 'western', 'central', 'remote', 'isolated', 'connected', 'urban', 'rural',
    'suburban', 'wilderness', 'frontier', 'border', 'interior', 'peripheral', 'offshore', 'underground',
    'overhead', 'lakeside', 'riverside', 'hilltop', 'cliffside', 'roadside', 'entrance', 'exit',
    'corridor', 'hallway', 'staircase', 'balcony', 'terrace', 'courtyard', 'basement', 'attic',
    'tower', 'dome', 'arch', 'column', 'pillar', 'beam', 'doorway', 'window',
    'ceiling', 'floor', 'wall', 'roof', 'foundation', 'chimney', 'bridge', 'tunnel',
    'path', 'trail', 'road', 'alley', 'intersection', 'dead-end', 'ramp', 'escalator',
    'elevator', 'landing', 'lobby', 'foyer', 'vestibule', 'portico', 'fragrant', 'musty',
    'smoky', 'salty', 'fresh', 'stale', 'sweet', 'acrid', 'echoing', 'silent',
    'rumbling', 'whistling', 'splashing', 'creaking', 'humming', 'dripping', 'pungent', 'earthy',
    'floral', 'rotten', 'briny', 'piney', 'metallic', 'chlorinated', 'landmark', 'monument',
    'ruin', 'oasis', 'sanctuary', 'refuge', 'labyrinth', 'maze', 'threshold', 'boundary',
    'horizon', 'summit', 'abyss', 'cavern', 'clearing', 'crossroads', 'fortress', 'haven',
    'hideout', 'overlook', 'panorama', 'passage', 'portal', 'gateway', 'outpost', 'enclave',
    'settlement', 'compound', 'district', 'quarter', 'precinct', 'borough', 'safe', 'dangerous',
    'treacherous', 'secure', 'protected', 'exposed', 'vulnerable', 'guarded', 'unstable', 'sturdy',
    'rickety', 'solid', 'fragile', 'resilient', 'collapsing', 'standing', 'contaminated', 'pure',
    'polluted', 'clean', 'toxic', 'hazardous', 'harmless', 'condemned', 'flowing', 'stagnant',
    'rushing', 'trickling', 'cascading', 'swirling', 'drifting', 'surging', 'meandering', 'branching',
    'converging', 'diverging', 'looping', 'zigzagging', 'spiraling', 'breathtaking', 'stunning', 'picturesque',
    'scenic', 'spectacular', 'impressive', 'immaculate', 'spotless', 'filthy', 'grimy', 'moated',
    'bridged', 'tunneled', 'graveled', 'tiered', 'cantilevered', 'vaulted', 'spired', 'buttressed',
    'signposted', 'unmarked', 'hidden', 'visible', 'prominent', 'obscured', 'illuminated', 'bordered',
    'landlocked', 'peninsular', 'archipelago', 'continental', 'equatorial', 'subtropical', 'gentrified', 'neglected',
    'thriving', 'declining', 'booming', 'developing', 'established', 'partitioned', 'zoned', 'rezoned',
    'annexed', 'incorporated', 'chartered', 'historic', 'heritage', 'landmarked', 'registered', 'conservation',
    'reclaimed', 'demolished', 'rebuilt', 'repurposed',
  ],

  objects: [
    'wooden', 'metal', 'plastic', 'glass', 'ceramic', 'rubber', 'leather', 'fabric',
    'paper', 'cardboard', 'stone', 'concrete', 'bamboo', 'copper', 'brass', 'steel',
    'iron', 'aluminum', 'titanium', 'chrome', 'gold', 'silver', 'bronze', 'tin',
    'porcelain', 'clay', 'wicker', 'cork', 'foam', 'silicone', 'vinyl', 'nylon',
    'cotton', 'wool', 'silk', 'linen', 'denim', 'velvet', 'suede', 'canvas',
    'fiberglass', 'acrylic', 'resin', 'enamel', 'graphite', 'pewter', 'ivory', 'bone',
    'round', 'square', 'rectangular', 'triangular', 'cylindrical', 'spherical', 'conical', 'flat',
    'curved', 'straight', 'twisted', 'spiral', 'angular', 'tapered', 'bulging', 'narrow',
    'wide', 'tall', 'short', 'tiny', 'huge', 'oversized', 'miniature', 'compact',
    'thick', 'thin', 'slim', 'bulky', 'hollow', 'solid', 'tubular', 'dome-shaped',
    'hexagonal', 'octagonal', 'oval', 'oblong', 'crescent', 'star-shaped', 'heart-shaped', 'irregular',
    'heavy', 'lightweight', 'featherlight', 'dense', 'airy', 'weighty', 'balanced', 'lopsided',
    'portable', 'immovable', 'cumbersome', 'handheld', 'pocket-sized', 'tabletop', 'floor-standing', 'wall-mounted',
    'hefty', 'substantial', 'negligible', 'massive', 'unwieldy', 'manageable', 'stackable', 'nestable',
    'smooth', 'rough', 'bumpy', 'ridged', 'grooved', 'textured', 'polished', 'matte',
    'glossy', 'shiny', 'dull', 'scratched', 'engraved', 'embossed', 'etched', 'stamped',
    'painted', 'coated', 'lacquered', 'varnished', 'stained', 'dyed', 'printed', 'woven',
    'knitted', 'braided', 'stitched', 'sewn', 'glued', 'welded', 'riveted', 'bolted',
    'sandblasted', 'hammered', 'brushed', 'dimpled', 'fluted', 'corrugated', 'perforated', 'quilted',
    'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'black', 'white',
    'gray', 'brown', 'pink', 'transparent', 'translucent', 'opaque', 'tinted', 'frosted',
    'multicolored', 'striped', 'checkered', 'dotted', 'patterned', 'plain', 'neon', 'pastel',
    'new', 'old', 'antique', 'vintage', 'modern', 'futuristic', 'worn', 'pristine',
    'broken', 'repaired', 'cracked', 'chipped', 'dented', 'bent', 'warped', 'faded',
    'rusty', 'corroded', 'tarnished', 'dusty', 'clean', 'weathered', 'patinated', 'aged',
    'useful', 'useless', 'essential', 'optional', 'versatile', 'specialized', 'multipurpose', 'single-use',
    'manual', 'automatic', 'electric', 'battery-powered', 'solar-powered', 'wind-up', 'rechargeable', 'disposable',
    'sharp', 'blunt', 'pointed', 'rounded', 'serrated', 'beveled', 'edged', 'tipped',
    'adjustable', 'fixed', 'collapsible', 'foldable', 'extendable', 'retractable', 'detachable', 'attachable',
    'locking', 'rotating', 'sliding', 'pivoting', 'rocking', 'rolling', 'spinning', 'swinging',
    'spring-loaded', 'lever-action', 'push-button', 'twist-on', 'snap-fit', 'screw-on', 'clip-on', 'velcro',
    'magnetic', 'conductive', 'insulating', 'waterproof', 'fireproof', 'shatterproof', 'bulletproof', 'rustproof',
    'flexible', 'rigid', 'elastic', 'brittle', 'durable', 'fragile', 'sturdy', 'flimsy',
    'absorbent', 'repellent', 'sticky', 'slippery', 'grippy', 'non-stick', 'reflective', 'luminous',
    'mirrored', 'colored', 'clear', 'cloudy', 'smoked', 'iridescent', 'glow-in-the-dark', 'heat-resistant',
    'loud', 'quiet', 'silent', 'buzzing', 'clicking', 'ticking', 'ringing', 'chiming',
    'squeaky', 'rattling', 'humming', 'whirring', 'beeping', 'whistling', 'clanking', 'jingling',
    'crunching', 'snapping', 'popping', 'hissing', 'sizzling', 'droning', 'pinging', 'clinking',
    'hot', 'cold', 'warm', 'cool', 'heated', 'chilled', 'insulated', 'thermal',
    'fragrant', 'odorless', 'musty', 'fresh', 'chemical', 'natural', 'scented', 'pungent',
    'cheap', 'expensive', 'valuable', 'worthless', 'priceless', 'affordable', 'luxurious', 'common',
    'rare', 'unique', 'custom', 'mass-produced', 'handmade', 'handcrafted', 'factory-made', 'imported',
    'collectible', 'heirloom', 'souvenir', 'replica', 'prototype', 'limited-edition', 'generic', 'simple',
    'complex', 'intricate', 'elaborate', 'basic', 'advanced', 'primitive', 'sophisticated', 'mechanical',
    'digital', 'analog', 'electronic', 'hydraulic', 'pneumatic', 'clockwork', 'motorized', 'indoor',
    'outdoor', 'household', 'industrial', 'medical', 'scientific', 'musical', 'artistic', 'kitchen',
    'bathroom', 'bedroom', 'garage', 'office', 'workshop', 'classroom', 'laboratory', 'everyday',
    'ceremonial', 'decorative', 'functional', 'ornamental', 'symbolic', 'practical', 'novelty', 'safe',
    'dangerous', 'protective', 'hazardous', 'childproof', 'padded', 'cushioned', 'reinforced', 'tangled',
    'neat', 'organized', 'messy', 'stacked', 'scattered', 'bundled', 'wrapped', 'sealed',
    'open', 'capped', 'corked', 'zippered', 'buttoned', 'snapped', 'clasped', 'hanging',
    'standing', 'leaning', 'floating', 'sinking', 'mounted', 'embedded', 'suspended', 'coiled',
    'folded', 'crumpled', 'flattened', 'inflated', 'deflated', 'compressed', 'expanded', 'washable',
    'dishwasher-safe', 'microwave-safe', 'oven-safe', 'food-safe', 'non-toxic', 'ergonomic', 'contoured', 'voice-activated',
    'touch-sensitive', 'motion-sensing', 'remote-controlled', 'telescoping', 'articulated', 'hinged', 'threaded', 'notched',
    'slotted', 'magnetized', 'charged', 'grounded', 'shielded', 'ventilated', 'pressurized', 'vacuum-sealed',
    'hermetic', 'monogrammed', 'personalized', 'branded', 'labeled', 'tagged', 'numbered', 'coded',
    'retro', 'contemporary', 'ornate', 'gear', 'lever', 'pulley', 'cam', 'piston',
    'valve', 'bracket', 'clamp', 'hook', 'wearable', 'implantable', 'prosthetic', 'orthopedic',
    'therapeutic', 'diagnostic', 'surgical', 'dental', 'optical', 'acoustic', 'spring', 'coil',
    'ratchet', 'toggle', 'dimmer', 'switch', 'knob', 'dial', 'slider', 'gauge',
    'meter', 'indicator', 'display', 'screen', 'lens', 'filter', 'prism', 'reflector',
    'diffuser', 'amplifier', 'dampener', 'buffer',
  ],

  professions: [
    'creative', 'analytical', 'technical', 'artistic', 'mathematical', 'linguistic', 'musical', 'athletic',
    'diplomatic', 'persuasive', 'observant', 'intuitive', 'logical', 'strategic', 'tactical', 'methodical',
    'inventive', 'resourceful', 'meticulous', 'precise', 'accurate', 'thorough', 'efficient', 'productive',
    'skilled', 'talented', 'gifted', 'trained', 'certified', 'licensed', 'qualified', 'experienced',
    'specialized', 'versatile', 'adaptable', 'flexible', 'dedicated', 'committed', 'passionate', 'driven',
    'bilingual', 'literate', 'numerate', 'eloquent', 'articulate', 'perceptive', 'insightful', 'visionary',
    'indoor', 'outdoor', 'office', 'field', 'laboratory', 'studio', 'workshop', 'factory',
    'hospital', 'courtroom', 'classroom', 'kitchen', 'stage', 'arena', 'ship', 'aircraft',
    'underground', 'underwater', 'airborne', 'remote', 'onsite', 'traveling', 'stationary', 'mobile',
    'urban', 'rural', 'suburban', 'international', 'local', 'regional', 'national', 'global',
    'sterile', 'dusty', 'noisy', 'quiet', 'cramped', 'spacious', 'hazardous', 'comfortable',
    'hammer', 'wrench', 'scalpel', 'brush', 'pen', 'keyboard', 'camera', 'microscope',
    'telescope', 'stethoscope', 'calculator', 'ruler', 'level', 'drill', 'saw', 'chisel',
    'needle', 'thread', 'wire', 'pipe', 'hose', 'rope', 'ladder', 'scaffold',
    'badge', 'uniform', 'helmet', 'goggles', 'gloves', 'boots', 'apron', 'mask',
    'clipboard', 'notebook', 'manual', 'blueprint', 'diagram', 'chart', 'map', 'compass',
    'syringe', 'forceps', 'thermometer', 'gauge', 'meter', 'probe', 'sensor', 'monitor',
    'brave', 'patient', 'caring', 'stern', 'charismatic', 'humble', 'confident', 'cautious',
    'ambitious', 'competitive', 'cooperative', 'independent', 'collaborative', 'assertive', 'empathetic', 'stoic',
    'disciplined', 'organized', 'spontaneous', 'reliable', 'punctual', 'trustworthy', 'honest', 'discreet',
    'calm', 'intense', 'focused', 'determined', 'persistent', 'resilient', 'tough', 'compassionate',
    'leader', 'follower', 'boss', 'subordinate', 'mentor', 'apprentice', 'expert', 'novice',
    'chief', 'senior', 'junior', 'intern', 'volunteer', 'freelance', 'consultant', 'contractor',
    'director', 'manager', 'supervisor', 'coordinator', 'specialist', 'generalist', 'assistant', 'associate',
    'founder', 'partner', 'shareholder', 'employee', 'colleague', 'peer', 'superior', 'protege',
    'educated', 'self-taught', 'academic', 'scholarly', 'studious', 'bookish', 'learned', 'worldly',
    'degree', 'diploma', 'certificate', 'apprenticeship', 'residency', 'fellowship', 'internship', 'training',
    'lecture', 'seminar', 'practice', 'rehearsal', 'simulation', 'exam', 'thesis', 'dissertation',
    'improvising', 'routine', 'unpredictable', 'structured', 'chaotic', 'systematic', 'procedural', 'hands-on',
    'theoretical', 'practical', 'abstract', 'physical', 'mental', 'emotional', 'spiritual', 'deadline',
    'overtime', 'shift', 'seasonal', 'permanent', 'temporary', 'part-time', 'full-time', 'on-call',
    'rotating', 'nocturnal', 'irregular', 'predictable', 'varied', 'repetitive', 'dynamic', 'medical',
    'legal', 'financial', 'educational', 'military', 'religious', 'scientific', 'technological', 'agricultural',
    'maritime', 'culinary', 'theatrical', 'journalistic', 'architectural', 'engineering', 'political', 'charitable',
    'commercial', 'governmental', 'judicial', 'legislative', 'executive', 'administrative', 'regulatory', 'pharmaceutical',
    'aerospace', 'automotive', 'textile', 'mining', 'forestry', 'fishing', 'energy', 'healing',
    'teaching', 'building', 'designing', 'investigating', 'protecting', 'serving', 'creating', 'repairing',
    'inspecting', 'enforcing', 'advising', 'negotiating', 'mediating', 'judging', 'sentencing', 'rescuing',
    'defending', 'prosecuting', 'counseling', 'coaching', 'mentoring', 'guiding', 'leading', 'diagnosing',
    'prescribing', 'operating', 'treating', 'analyzing', 'researching', 'experimenting', 'documenting', 'performing',
    'entertaining', 'composing', 'directing', 'producing', 'editing', 'publishing', 'broadcasting', 'welding',
    'soldering', 'wiring', 'plumbing', 'painting', 'sculpting', 'drafting', 'surveying', 'dangerous',
    'safe', 'risky', 'stressful', 'relaxed', 'demanding', 'cushy', 'grueling', 'life-threatening',
    'stable', 'volatile', 'secure', 'precarious', 'exhausting', 'rewarding', 'thankless', 'wealthy',
    'underpaid', 'prestigious', 'respected', 'undervalued', 'famous', 'anonymous', 'notorious', 'powerful',
    'influential', 'essential', 'expendable', 'irreplaceable', 'common', 'rare', 'elite', 'ethical',
    'corrupt', 'altruistic', 'selfish', 'principled', 'pragmatic', 'idealistic', 'cynical', 'oath',
    'code', 'duty', 'honor', 'service', 'obligation', 'responsibility', 'accountability', 'uniformed',
    'suited', 'robed', 'costumed', 'armored', 'plainclothes', 'disguised', 'identifiable', 'sworn',
    'elected', 'appointed', 'hired', 'drafted', 'recruited', 'promoted', 'retired', 'celebrated',
    'controversial', 'pioneering', 'traditional', 'revolutionary', 'conservative', 'progressive', 'radical', 'overworked',
    'underemployed', 'moonlighting', 'sabbatical', 'furloughed', 'suspended', 'reinstated', 'tenured', 'entrepreneurial',
    'corporate', 'nonprofit', 'startup', 'salaried', 'hourly', 'commissioned', 'tipped', 'networking',
    'lobbying', 'fundraising', 'campaigning', 'canvassing', 'advocating', 'auditing', 'bookkeeping', 'invoicing',
    'budgeting', 'forecasting', 'appraising', 'assessing', 'evaluating', 'interviewing', 'onboarding', 'patrolling',
    'surveilling', 'monitoring', 'dispatching', 'responding', 'evacuating', 'triaging', 'stabilizing', 'coding',
    'debugging', 'deploying', 'testing', 'optimizing', 'scaling', 'migrating', 'archiving', 'illustrating',
    'animating', 'storyboarding', 'screenwriting', 'copywriting', 'proofreading', 'translating', 'interpreting', 'auctioning',
    'brokering', 'underwriting', 'insuring', 'litigating', 'arbitrating', 'notarizing', 'certifying', 'excavating',
    'demolishing', 'constructing', 'landscaping', 'paving', 'roofing', 'glazing', 'plastering', 'tiling',
    'flooring', 'framing', 'insulating', 'ventilating', 'irrigating', 'harvesting', 'processing', 'bottling',
    'distilling', 'brewing', 'fermenting', 'curing', 'tanning', 'milling', 'forging', 'casting',
    'tempering', 'annealing', 'quenching', 'polishing',
  ],

  activities: [
    'intense', 'relaxing', 'exhausting', 'effortless', 'grueling', 'gentle', 'vigorous', 'moderate',
    'strenuous', 'leisurely', 'demanding', 'casual', 'hardcore', 'beginner', 'advanced', 'extreme',
    'challenging', 'easy', 'difficult', 'simple', 'complex', 'technical', 'basic', 'elaborate',
    'fast-paced', 'slow-paced', 'steady', 'explosive', 'sustained', 'interval', 'continuous', 'intermittent',
    'punishing', 'forgiving', 'brutal', 'mellow', 'taxing', 'restful', 'draining', 'rejuvenating',
    'indoor', 'outdoor', 'underwater', 'aerial', 'underground', 'mountain', 'beach', 'forest',
    'urban', 'rural', 'backyard', 'park', 'gym', 'studio', 'arena', 'court',
    'field', 'track', 'trail', 'road', 'river', 'lake', 'ocean', 'pool',
    'rooftop', 'basement', 'garage', 'kitchen', 'garden', 'balcony', 'patio', 'deck',
    'clifftop', 'valley', 'desert', 'tundra', 'cave', 'island', 'harbor', 'meadow',
    'solo', 'partner', 'team', 'group', 'crowd', 'family', 'friends', 'strangers',
    'competitive', 'cooperative', 'collaborative', 'individual', 'communal', 'social', 'private', 'public',
    'spectator', 'participant', 'leader', 'follower', 'coach', 'student', 'teacher', 'rival',
    'mentor', 'amateur', 'professional', 'volunteer', 'opponent', 'teammate', 'referee', 'judge',
    'ball', 'bat', 'racket', 'paddle', 'club', 'stick', 'rod', 'pole',
    'net', 'goal', 'hoop', 'target', 'board', 'mat', 'rope', 'harness',
    'helmet', 'gloves', 'pads', 'shoes', 'boots', 'cleats', 'goggles', 'mask',
    'wheel', 'blade', 'fin', 'sail', 'oar', 'pedal', 'handle', 'grip',
    'brush', 'needle', 'thread', 'yarn', 'clay', 'paint', 'pencil', 'canvas',
    'whistle', 'stopwatch', 'scoreboard', 'cone', 'flag', 'baton', 'disc', 'puck',
    'running', 'jumping', 'throwing', 'catching', 'kicking', 'hitting', 'swinging', 'spinning',
    'rolling', 'sliding', 'balancing', 'stretching', 'bending', 'twisting', 'lifting', 'pulling',
    'pushing', 'squeezing', 'gripping', 'releasing', 'aiming', 'launching', 'landing', 'falling',
    'flipping', 'tumbling', 'cartwheeling', 'handstanding', 'vaulting', 'hurdling', 'sprinting', 'jogging',
    'paddling', 'rowing', 'steering', 'braking', 'accelerating', 'coasting', 'gliding', 'floating',
    'ducking', 'dodging', 'weaving', 'lunging', 'pivoting', 'shuffling', 'skipping', 'hopping',
    'rhythmic', 'timed', 'scored', 'judged', 'measured', 'counted', 'clocked', 'ranked',
    'synchronized', 'freestyle', 'choreographed', 'improvised', 'rehearsed', 'spontaneous', 'planned', 'random',
    'fast', 'slow', 'quick', 'deliberate', 'precise', 'sloppy', 'graceful', 'clumsy',
    'tempo', 'beat', 'cadence', 'pulse', 'flow', 'momentum', 'pace', 'timing',
    'loud', 'quiet', 'silent', 'musical', 'noisy', 'peaceful', 'meditative', 'focused',
    'sweaty', 'breathless', 'exhilarating', 'calming', 'thrilling', 'boring', 'exciting', 'monotonous',
    'painful', 'soothing', 'refreshing', 'tiring', 'energizing', 'invigorating', 'numbing', 'tingling',
    'adrenaline', 'endorphin', 'zen', 'euphoric', 'dizzy', 'winded', 'pumped', 'drained',
    'sunny', 'rainy', 'snowy', 'windy', 'stormy', 'cloudy', 'foggy', 'icy',
    'summer', 'winter', 'spring', 'autumn', 'seasonal', 'year-round', 'warm-weather', 'cold-weather',
    'tropical', 'arctic', 'temperate', 'arid', 'humid', 'breezy', 'scorching', 'frigid',
    'daily', 'weekly', 'monthly', 'occasional', 'regular', 'sporadic', 'marathon', 'sprint',
    'brief', 'lengthy', 'all-day', 'overnight', 'weekend', 'morning', 'evening', 'midnight',
    'hourly', 'annual', 'biweekly', 'nonstop', 'periodic', 'burst', 'dangerous', 'safe',
    'risky', 'reckless', 'cautious', 'protected', 'unprotected', 'supervised', 'controlled', 'unpredictable',
    'calculated', 'daring', 'foolish', 'brave', 'insured', 'liability', 'skilled', 'expert',
    'novice', 'intermediate', 'masterful', 'practiced', 'natural', 'trained', 'instinctive', 'learned',
    'disciplined', 'wild', 'polished', 'raw', 'refined', 'developing', 'creative', 'expressive',
    'abstract', 'realistic', 'colorful', 'monochrome', 'detailed', 'minimalist', 'traditional', 'modern',
    'experimental', 'classical', 'folk', 'contemporary', 'avant-garde', 'rustic', 'freeform', 'structured',
    'improvisational', 'scripted', 'organic', 'geometric', 'fluid', 'rigid', 'messy', 'clean',
    'dusty', 'wet', 'dry', 'muddy', 'sandy', 'grassy', 'addictive', 'therapeutic',
    'spiritual', 'cultural', 'historical', 'educational', 'productive', 'wasteful', 'rewarding', 'frustrating',
    'satisfying', 'disappointing', 'surprising', 'predictable', 'transformative', 'routine', 'hobby', 'sport',
    'craft', 'art', 'game', 'exercise', 'practice', 'ritual', 'tournament', 'match',
    'race', 'contest', 'exhibition', 'performance', 'recital', 'showcase', 'warmup', 'cooldown',
    'stretch', 'drill', 'scrimmage', 'qualifier', 'final', 'overtime', 'uphill', 'downhill',
    'cross-country', 'long-distance', 'short-distance', 'relay', 'obstacle', 'endurance', 'high-intensity', 'low-impact',
    'full-body', 'upper-body', 'lower-body', 'core', 'cardio', 'strength', 'flexibility', 'agility',
    'coordination', 'balance', 'speed', 'power', 'stamina', 'recovery', 'hydration', 'nutrition',
    'scoring', 'defending', 'attacking', 'blocking', 'passing', 'dribbling', 'shooting', 'serving',
    'backstroke', 'breaststroke', 'butterfly', 'medley', 'trekking', 'backpacking', 'mountaineering', 'rappelling',
    'belaying', 'bouldering', 'caving', 'spelunking', 'plein-air', 'still-life', 'portrait', 'landscape',
    'mixed-media', 'beginner-friendly', 'family-friendly', 'age-appropriate', 'inclusive', 'adaptive', 'accessible', 'universal',
    'sunrise', 'sunset', 'moonlit', 'torchlit', 'floodlit', 'starlit', 'twilight', 'dawn',
    'dusk', 'nighttime', 'daytime', 'pre-dawn', 'midday', 'afternoon', 'post-workout', 'pre-game',
    'halftime', 'penalty', 'foul', 'disqualification',
  ],

  movies: [
    'action', 'comedy', 'drama', 'horror', 'thriller', 'romance', 'mystery', 'fantasy',
    'western', 'musical', 'documentary', 'animated', 'noir', 'satire', 'parody', 'biopic',
    'heist', 'courtroom', 'disaster', 'espionage', 'gangster', 'slasher', 'zombie', 'vampire',
    'superhero', 'space', 'war', 'prison', 'sports', 'coming-of-age', 'road-trip', 'survival',
    'kaiju', 'anthology', 'mockumentary', 'found-footage', 'whodunit', 'techno-thriller', 'swashbuckler', 'spaghetti',
    'suspenseful', 'heartwarming', 'terrifying', 'hilarious', 'tragic', 'uplifting', 'dark', 'lighthearted',
    'intense', 'relaxed', 'eerie', 'whimsical', 'gritty', 'polished', 'raw', 'dreamy',
    'melancholic', 'euphoric', 'tense', 'peaceful', 'chaotic', 'somber', 'playful', 'brooding',
    'nostalgic', 'futuristic', 'timeless', 'dated', 'fresh', 'stale', 'vibrant', 'muted',
    'chilling', 'sentimental', 'sardonic', 'absurd', 'deadpan', 'campy', 'earnest', 'cynical',
    'hero', 'villain', 'sidekick', 'mentor', 'antihero', 'damsel', 'outlaw', 'detective',
    'spy', 'soldier', 'scientist', 'alien', 'robot', 'ghost', 'monster', 'wizard',
    'orphan', 'chosen-one', 'underdog', 'genius', 'fool', 'loner', 'leader', 'rebel',
    'partner', 'rival', 'traitor', 'savior', 'victim', 'survivor', 'witness', 'narrator',
    'assassin', 'fugitive', 'prisoner', 'king', 'peasant', 'prophet', 'con-artist', 'vigilante',
    'twist', 'cliffhanger', 'flashback', 'foreshadowing', 'montage', 'voiceover', 'prologue', 'epilogue',
    'betrayal', 'revenge', 'redemption', 'sacrifice', 'escape', 'chase', 'rescue', 'siege',
    'trial', 'duel', 'showdown', 'ambush', 'invasion', 'discovery', 'revelation', 'confession',
    'journey', 'quest', 'mission', 'investigation', 'conspiracy', 'prophecy', 'curse', 'transformation',
    'kidnapping', 'ransom', 'blackmail', 'framing', 'alibi', 'coverup', 'double-cross', 'clue',
    'widescreen', 'close-up', 'panoramic', 'aerial', 'underwater', 'slow-motion', 'time-lapse', 'tracking',
    'handheld', 'steady', 'shaky', 'smooth', 'zooming', 'panning', 'tilting', 'rotating',
    'colorful', 'black-and-white', 'sepia', 'neon', 'shadowy', 'sunlit', 'moonlit', 'candlelit',
    'blurry', 'sharp', 'grainy', 'crisp', 'saturated', 'desaturated', 'overexposed', 'silhouetted',
    'split-screen', 'freeze-frame', 'dolly', 'crane', 'dutch-angle', 'bird-eye', 'worm-eye', 'POV',
    'orchestral', 'electronic', 'acoustic', 'silent', 'loud', 'whispered', 'echoing', 'thundering',
    'soundtrack', 'score', 'theme', 'ballad', 'anthem', 'jingle', 'lullaby', 'hymn',
    'dialogue', 'monologue', 'scream', 'whisper', 'gunshot', 'explosion', 'siren', 'heartbeat',
    'synthesizer', 'choir', 'drums', 'strings', 'brass', 'piano', 'guitar', 'silence',
    'medieval', 'Victorian', 'modern', 'prehistoric', 'colonial', 'prohibition', 'wartime', 'renaissance',
    'dystopian', 'utopian', 'post-apocalyptic', 'cyberpunk', 'steampunk', 'gothic', 'tropical', 'arctic',
    'urban', 'rural', 'suburban', 'wilderness', 'underground', 'orbital', 'interdimensional', 'otherworldly',
    'prohibition-era', 'cold-war', 'frontier', 'roaring-twenties', 'ancient', 'biblical', 'samurai', 'viking',
    'blockbuster', 'indie', 'low-budget', 'high-budget', 'mainstream', 'arthouse', 'cult', 'experimental',
    'sequel', 'prequel', 'reboot', 'remake', 'spinoff', 'adaptation', 'original', 'franchise',
    'award-winning', 'nominated', 'overlooked', 'banned', 'censored', 'controversial', 'acclaimed', 'panned',
    'directed', 'produced', 'written', 'scored', 'edited', 'cast', 'filmed', 'released',
    'CGI', 'practical-effects', 'stop-motion', 'rotoscoped', 'motion-capture', 'miniature', 'matte-painting', 'prosthetics',
    'classic', 'forgettable', 'iconic', 'polarizing', 'beloved', 'hated', 'underrated', 'overrated',
    'groundbreaking', 'derivative', 'innovative', 'formulaic', 'predictable', 'surprising', 'shocking', 'boring',
    'emotional', 'intellectual', 'visceral', 'cerebral', 'entertaining', 'thought-provoking', 'escapist', 'realistic',
    'family-friendly', 'mature', 'graphic', 'tame', 'explicit', 'subtle', 'provocative', 'wholesome',
    'crying', 'laughing', 'screaming', 'cheering', 'gasping', 'cringing', 'smiling', 'frowning',
    'terrified', 'inspired', 'disgusted', 'amazed', 'confused', 'satisfied', 'frustrated', 'moved',
    'haunted', 'delighted', 'devastated', 'riveted', 'bored', 'captivated', 'disturbed', 'enchanted',
    'fast', 'slow', 'building', 'climactic', 'anticlimactic', 'uneven', 'relentless', 'measured',
    'episodic', 'linear', 'nonlinear', 'fragmented', 'seamless', 'choppy', 'flowing', 'jarring',
    'opening', 'closing', 'middle', 'act', 'scene', 'sequence', 'frame', 'shot',
    'sword', 'gun', 'car', 'spaceship', 'mask', 'cape', 'ring', 'map',
    'potion', 'bomb', 'shield', 'crown', 'throne', 'mirror', 'diary', 'letter',
    'treasure', 'artifact', 'weapon', 'vehicle', 'costume', 'disguise', 'gadget', 'device',
    'love', 'death', 'power', 'freedom', 'justice', 'identity', 'family', 'friendship',
    'forgiveness', 'obsession', 'madness', 'greed', 'honor', 'hope', 'despair', 'corruption',
    'innocence', 'destiny', 'fate', 'ambition', 'loyalty', 'isolation', 'belonging', 'epic',
    'intimate', 'sprawling', 'contained', 'ambitious', 'modest', 'lavish', 'sparse', 'beautiful',
    'ugly', 'stunning', 'hideous', 'gorgeous', 'grotesque', 'elegant', 'crude', 'clever',
    'stupid', 'brilliant', 'dumb', 'witty', 'corny', 'dull', 'razor-sharp', 'believable',
    'plausible', 'ridiculous', 'authentic', 'fake', 'genuine', 'contrived', 'crossover', 'ensemble',
    'standalone', 'serialized', 'self-contained', 'open-ended', 'concluded', 'director-cut', 'theatrical', 'extended',
    'unrated', 'restored', 'remastered', 'dubbing', 'subtitled', 'captioned', 'voice-acted', 'overdubbed',
    'localized', 'stunt', 'choreography', 'wirework', 'pyrotechnics', 'puppetry', 'animatronics', 'hologram',
    'projection', 'protagonist', 'antagonist', 'deuteragonist', 'ensemble-cast', 'cameo', 'extra', 'stand-in',
    'stunt-double', 'body-double', 'voice-over', 'dubstep',
  ],

};

class ClueDeck {
  constructor(listName) {
    this.listName = listName || 'animals';
    this.dealtThisStep = new Set();
    this.playedThisGame = new Set();
  }

  static getLists() {
    return Object.keys(CLUE_LISTS);
  }

  setList(listName) {
    if (CLUE_LISTS[listName]) {
      this.listName = listName;
      this.dealtThisStep.clear();
      this.playedThisGame.clear();
    }
  }

  startStep() {
    this.dealtThisStep.clear();
  }

  markPlayed(word) {
    this.playedThisGame.add(word);
  }

  draw(count) {
    const wordList = CLUE_LISTS[this.listName] || CLUE_LISTS.animals;
    const available = wordList.filter(w => !this.dealtThisStep.has(w) && !this.playedThisGame.has(w));

    if (available.length < count) {
      this.playedThisGame.clear();
      return this.draw(count);
    }

    const shuffled = [...available].sort(() => Math.random() - 0.5);
    const hand = shuffled.slice(0, count);
    hand.forEach(w => this.dealtThisStep.add(w));
    return hand;
  }

  resetRound() {
    this.dealtThisStep.clear();
    this.playedThisGame.clear();
  }
}

module.exports = ClueDeck;
