const CLUE_LISTS = {
  animals: [
    'striped', 'spotted', 'furry', 'feathered', 'scaly', 'slimy', 'spiny', 'fluffy',
    'hairy', 'bald', 'wrinkled', 'sleek', 'muscular', 'plump', 'lean', 'bulky',
    'tiny', 'massive', 'enormous', 'miniature', 'long', 'stubby', 'tall', 'squat',
    'horned', 'tusked', 'fanged', 'clawed', 'webbed', 'winged', 'finned', 'tailed',
    'armored', 'shelled', 'hoofed', 'pouched', 'beaked', 'whiskered', 'maned', 'crested',
    'black', 'white', 'brown', 'golden', 'orange', 'red', 'blue', 'green',
    'gray', 'silver', 'pink', 'yellow', 'purple', 'tan', 'cream', 'copper',
    'camouflaged', 'patterned', 'multicolored', 'pale', 'dark', 'colorful', 'drab',
    'aggressive', 'docile', 'timid', 'curious', 'playful', 'lazy', 'alert', 'cunning',
    'loyal', 'territorial', 'social', 'solitary', 'migratory', 'nomadic', 'patient', 'restless',
    'fierce', 'gentle', 'stubborn', 'obedient', 'mischievous', 'cautious', 'bold', 'shy',
    'intelligent', 'clever', 'trainable', 'wild', 'tame', 'skittish', 'calm',
    'fast', 'slow', 'graceful', 'clumsy', 'agile', 'lumbering',
    'slithering', 'galloping', 'soaring', 'burrowing', 'darting',
    'gliding', 'hovering', 'waddling', 'prancing', 'prowling', 'stalking', 'charging',
    'floating', 'pouncing', 'scurrying', 'trotting', 'sprinting', 'creeping', 'swooping',
    'roaring', 'growling', 'hissing', 'chirping', 'howling', 'barking', 'purring', 'squeaking',
    'trumpeting', 'croaking', 'buzzing', 'chattering', 'screeching', 'cooing', 'bellowing', 'whistling',
    'snorting', 'grunting', 'snarling', 'whimpering',
    'tropical', 'arctic', 'desert', 'forest', 'mountain', 'ocean', 'freshwater', 'swamp',
    'underground', 'coastal', 'grassland', 'tundra', 'jungle', 'cave', 'reef', 'island',
    'polar', 'wetland', 'savanna', 'urban', 'rural',
    'nocturnal', 'nesting', 'perched', 'submerged', 'roaming', 'hibernating', 'shedding',
    'carnivorous', 'herbivorous', 'omnivorous', 'grazing', 'foraging',
    'venomous', 'poisonous', 'gnawing', 'ambushing',
    'pack', 'herd', 'flock', 'swarm', 'colony', 'pride', 'school', 'pod',
    'paired', 'lone', 'alpha', 'maternal', 'communal', 'cooperative', 'competitive',
    'stinging', 'biting', 'scratching', 'kicking', 'ramming', 'fleeing', 'hiding', 'coiling',
    'predator', 'prey', 'hunter', 'scavenger', 'companion', 'pest',
    'swimmer', 'flyer', 'runner', 'climber', 'digger', 'diver', 'jumper', 'crawler',
    'mud', 'sand', 'coral', 'kelp', 'grass', 'bark', 'ice', 'snow',
    'rock', 'den', 'nest', 'burrow', 'hive', 'web', 'shell', 'cocoon',
    'branch', 'canopy', 'shoreline',
    'majestic', 'fearsome', 'adorable', 'ugly', 'beautiful', 'elegant', 'grotesque',
    'harmless', 'dangerous', 'cuddly', 'prickly', 'stealthy', 'smelly',
    'wet', 'dry', 'warm', 'cold', 'rough', 'smooth', 'soft', 'hard',
    'flexible', 'fragile', 'tough',
    'endangered', 'extinct', 'rare', 'ancient', 'domesticated', 'exotic', 'invasive',
    'claw', 'antler', 'tusk', 'horn', 'fang', 'gill', 'tentacle',
    'wiry', 'stocky', 'lanky', 'rotund', 'lithe', 'spindly',
    'migrating', 'mating', 'courting', 'nursing', 'preening', 'grooming',
  ],

  food: [
    'sweet', 'sour', 'salty', 'bitter', 'savory', 'umami', 'tangy', 'tart',
    'spicy', 'mild', 'bland', 'rich', 'sharp', 'pungent', 'zesty', 'mellow',
    'smoky', 'earthy', 'nutty', 'fruity', 'floral', 'herbal', 'minty', 'peppery',
    'garlicky', 'buttery', 'cheesy', 'vinegary', 'briny', 'citrusy', 'chocolatey', 'caramelized',
    'honeyed', 'syrupy', 'bittersweet', 'acidic', 'toasty',
    'crispy', 'crunchy', 'chewy', 'tender', 'flaky', 'crumbly', 'smooth', 'creamy',
    'gooey', 'sticky', 'silky', 'velvety', 'grainy', 'lumpy', 'mushy', 'fluffy',
    'dense', 'airy', 'foamy', 'bubbly', 'fizzy', 'gelatinous', 'rubbery', 'brittle',
    'firm', 'soft', 'hard', 'moist', 'dry', 'juicy', 'succulent', 'springy',
    'spongy', 'doughy', 'powdery', 'chunky', 'oily', 'crackly', 'stringy', 'waxy',
    'hot', 'cold', 'warm', 'chilled', 'frozen', 'steaming', 'icy', 'room-temperature',
    'raw', 'fried', 'baked', 'grilled', 'roasted', 'steamed', 'boiled', 'sauteed',
    'smoked', 'cured', 'pickled', 'fermented', 'dried', 'seared', 'glazed', 'marinated',
    'wrapped', 'sliced', 'diced', 'chopped', 'minced', 'shredded', 'blended',
    'mashed', 'rolled', 'folded', 'stuffed', 'seasoned', 'charred', 'toasted', 'broiled',
    'braised', 'poached', 'stir-fried', 'infused', 'reduced', 'layered', 'candied',
    'white', 'red', 'green', 'yellow', 'orange', 'purple', 'colorful', 'pale',
    'dark', 'golden', 'brown', 'glossy', 'clear', 'cloudy',
    'round', 'flat', 'thin', 'thick', 'long', 'square', 'spiral', 'twisted',
    'Italian', 'Mexican', 'Japanese', 'Chinese', 'Indian', 'French', 'Thai', 'Greek',
    'Korean', 'Vietnamese', 'American', 'Brazilian', 'Spanish', 'Caribbean', 'Mediterranean', 'Turkish',
    'German', 'Filipino', 'Moroccan', 'Peruvian', 'Lebanese', 'Hawaiian', 'Cajun', 'Cuban',
    'breakfast', 'lunch', 'dinner', 'snack', 'appetizer', 'entree', 'dessert', 'side',
    'brunch', 'holiday', 'comfort', 'street', 'gourmet', 'homemade', 'takeout', 'buffet',
    'organic', 'fresh', 'canned', 'instant', 'processed', 'seasonal', 'local', 'imported',
    'vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'kosher', 'halal', 'keto', 'paleo',
    'traditional', 'classic', 'fusion', 'rustic', 'elegant', 'authentic', 'simple', 'complex',
    'delicious', 'flavorful', 'appetizing', 'disgusting', 'heavenly', 'satisfying',
    'filling', 'refreshing', 'nourishing', 'indulgent', 'decadent', 'fragrant', 'balanced',
    'flour', 'sugar', 'butter', 'egg', 'milk', 'cream', 'oil', 'salt',
    'pepper', 'garlic', 'cheese', 'bread', 'rice', 'pasta', 'ginger', 'onion',
    'sauce', 'broth', 'gravy', 'dressing', 'condiment', 'garnish', 'herb', 'spice',
    'yeast', 'dough', 'batter', 'crust', 'frosting', 'icing', 'stock', 'vinegar',
    'light', 'heavy', 'tiny', 'oversized', 'natural', 'luxurious', 'cheap', 'expensive',
    'al-dente', 'well-done', 'medium-rare', 'melt-in-mouth', 'pillowy', 'intense', 'subtle',
  ],

  places: [
    'peaceful', 'chaotic', 'eerie', 'lively', 'quiet', 'noisy', 'serene', 'bustling',
    'haunted', 'magical', 'mysterious', 'sacred', 'welcoming', 'hostile', 'abandoned', 'cozy',
    'gloomy', 'cheerful', 'romantic', 'majestic', 'humble', 'turbulent',
    'vibrant', 'somber', 'festive', 'solemn', 'wild', 'tense', 'relaxed', 'inspiring',
    'depressing', 'dreary', 'inviting', 'foreboding', 'charming', 'bleak', 'idyllic',
    'sinister', 'quaint', 'imposing',
    'vast', 'tiny', 'cramped', 'spacious', 'narrow', 'wide', 'towering',
    'sprawling', 'compact', 'endless', 'confined', 'intimate', 'massive',
    'deep', 'shallow', 'low', 'cavernous', 'grand',
    'rocky', 'sandy', 'muddy', 'grassy', 'paved', 'cobblestone', 'dirt', 'dusty',
    'wet', 'dry', 'frozen', 'flooded', 'cracked', 'smooth', 'rough', 'hilly',
    'flat', 'steep', 'sloping', 'winding', 'straight', 'curved', 'circular', 'jagged',
    'tropical', 'arctic', 'arid', 'humid', 'temperate', 'windy', 'rainy', 'sunny',
    'foggy', 'misty', 'snowy', 'icy', 'stormy', 'overcast', 'clear', 'hazy',
    'hot', 'cold', 'warm', 'cool', 'freezing', 'sweltering', 'mild', 'harsh',
    'ancient', 'modern', 'medieval', 'futuristic', 'colonial', 'Victorian', 'ruined',
    'pristine', 'crumbling', 'restored', 'renovated', 'dilapidated', 'weathered',
    'worn', 'rusty', 'mossy', 'overgrown', 'barren', 'lush', 'timeless',
    'stone', 'brick', 'wooden', 'concrete', 'glass', 'steel', 'marble', 'thatched',
    'tiled', 'painted', 'carved', 'walled', 'gated', 'open', 'enclosed',
    'roofed', 'adobe', 'bamboo', 'limestone', 'timber',
    'bright', 'dark', 'dim', 'sunlit', 'moonlit', 'candlelit', 'neon',
    'glowing', 'flickering', 'sparkling', 'murky', 'starlit',
    'crowded', 'empty', 'populated', 'deserted', 'sparse', 'teeming',
    'public', 'private', 'restricted', 'accessible', 'exclusive', 'communal', 'commercial', 'residential',
    'industrial', 'agricultural', 'military', 'religious', 'educational', 'touristy', 'local',
    'coastal', 'inland', 'mountainous', 'underwater', 'floating', 'valley', 'plateau',
    'remote', 'connected', 'urban', 'rural', 'suburban', 'wilderness', 'frontier',
    'hallway', 'staircase', 'balcony', 'terrace', 'courtyard', 'basement', 'attic',
    'tower', 'dome', 'arch', 'doorway', 'window', 'ceiling', 'floor', 'wall',
    'roof', 'bridge', 'tunnel', 'path', 'trail', 'road', 'alley', 'ramp',
    'fragrant', 'musty', 'smoky', 'salty', 'fresh', 'stale', 'earthy', 'echoing',
    'silent', 'rumbling', 'splashing', 'creaking', 'humming', 'dripping',
    'landmark', 'ruin', 'oasis', 'sanctuary', 'maze', 'horizon',
    'summit', 'cavern', 'clearing', 'crossroads', 'fortress', 'haven', 'overlook',
    'gateway', 'outpost', 'settlement', 'district', 'quarter',
    'safe', 'dangerous', 'treacherous', 'secure', 'exposed', 'guarded', 'fragile', 'solid',
    'polluted', 'clean', 'flowing', 'stagnant', 'rushing',
    'breathtaking', 'stunning', 'scenic', 'immaculate', 'filthy', 'grimy',
    'hidden', 'prominent', 'illuminated', 'thriving', 'declining', 'historic', 'neglected',
  ],

  objects: [
    'wooden', 'metal', 'plastic', 'glass', 'ceramic', 'rubber', 'leather', 'fabric',
    'paper', 'cardboard', 'stone', 'concrete', 'bamboo', 'copper', 'brass', 'steel',
    'iron', 'aluminum', 'chrome', 'gold', 'silver', 'bronze', 'porcelain', 'clay',
    'wicker', 'foam', 'silicone', 'vinyl', 'nylon', 'cotton', 'wool', 'silk',
    'linen', 'denim', 'velvet', 'suede', 'canvas', 'acrylic',
    'round', 'square', 'rectangular', 'triangular', 'cylindrical', 'flat', 'curved',
    'straight', 'twisted', 'spiral', 'angular', 'tapered', 'narrow', 'wide', 'tall',
    'short', 'tiny', 'huge', 'oversized', 'miniature', 'compact', 'thick', 'thin',
    'bulky', 'hollow', 'solid', 'dome-shaped', 'oval', 'irregular',
    'heavy', 'lightweight', 'dense', 'airy', 'portable', 'handheld', 'pocket-sized', 'tabletop',
    'floor-standing', 'wall-mounted', 'unwieldy',
    'smooth', 'rough', 'bumpy', 'grooved', 'textured', 'polished', 'matte',
    'glossy', 'dull', 'scratched', 'engraved', 'embossed', 'painted',
    'coated', 'stained', 'dyed', 'printed', 'woven', 'stitched',
    'glued', 'welded', 'bolted', 'braided',
    'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'black', 'white',
    'gray', 'brown', 'pink', 'transparent', 'translucent', 'opaque', 'tinted', 'frosted',
    'multicolored', 'striped', 'checkered', 'dotted', 'patterned', 'plain', 'neon', 'pastel',
    'new', 'old', 'antique', 'vintage', 'modern', 'worn', 'pristine', 'broken',
    'repaired', 'cracked', 'chipped', 'dented', 'bent', 'warped', 'rusty',
    'dusty', 'clean', 'weathered', 'aged',
    'useful', 'useless', 'essential', 'versatile', 'specialized', 'single-use',
    'manual', 'automatic', 'electric', 'solar-powered', 'rechargeable', 'disposable',
    'sharp', 'blunt', 'pointed', 'serrated', 'edged',
    'adjustable', 'fixed', 'collapsible', 'extendable', 'retractable', 'detachable',
    'locking', 'rotating', 'sliding', 'rocking', 'rolling', 'swinging',
    'push-button', 'twist-on', 'snap-fit', 'screw-on', 'clip-on', 'magnetic',
    'waterproof', 'fireproof', 'shatterproof', 'flexible', 'rigid',
    'durable', 'fragile', 'flimsy', 'absorbent', 'sticky', 'slippery', 'grippy',
    'reflective', 'luminous', 'cloudy', 'iridescent', 'glow-in-the-dark',
    'loud', 'quiet', 'silent', 'buzzing', 'clicking', 'ringing',
    'squeaky', 'rattling', 'whirring', 'beeping', 'whistling', 'jingling',
    'hot', 'cold', 'warm', 'cool', 'insulated',
    'fragrant', 'odorless', 'musty', 'fresh', 'chemical', 'natural',
    'cheap', 'expensive', 'valuable', 'worthless', 'luxurious', 'common', 'rare',
    'custom', 'handmade', 'mass-produced', 'collectible',
    'simple', 'complex', 'basic', 'advanced', 'primitive',
    'digital', 'analog', 'electronic', 'motorized', 'indoor', 'outdoor', 'household',
    'medical', 'musical', 'artistic', 'kitchen', 'everyday', 'decorative', 'functional',
    'novelty', 'safe', 'dangerous', 'protective', 'childproof',
    'padded', 'sealed', 'open', 'capped', 'zippered', 'buttoned', 'clasped',
    'hanging', 'standing', 'floating', 'mounted', 'coiled', 'folded', 'inflated',
    'deflated', 'compressed', 'washable', 'ergonomic', 'voice-activated', 'remote-controlled',
    'branded', 'labeled', 'ornate',
  ],

  professions: [
    'creative', 'analytical', 'technical', 'artistic', 'mathematical', 'musical', 'athletic',
    'diplomatic', 'persuasive', 'observant', 'logical', 'strategic', 'methodical', 'inventive',
    'resourceful', 'meticulous', 'precise', 'efficient', 'skilled',
    'trained', 'certified', 'qualified', 'experienced', 'specialized', 'versatile',
    'dedicated', 'passionate', 'bilingual', 'articulate', 'perceptive',
    'indoor', 'outdoor', 'office', 'field', 'laboratory', 'studio', 'workshop', 'factory',
    'hospital', 'courtroom', 'classroom', 'kitchen', 'stage', 'arena', 'ship', 'aircraft',
    'underground', 'underwater', 'remote', 'traveling', 'stationary', 'mobile',
    'urban', 'rural', 'international', 'local', 'national', 'global', 'sterile', 'noisy',
    'hazardous', 'comfortable',
    'hammer', 'wrench', 'scalpel', 'brush', 'pen', 'keyboard', 'camera', 'microscope',
    'stethoscope', 'calculator', 'ruler', 'drill', 'saw', 'needle', 'wire', 'rope',
    'ladder', 'badge', 'uniform', 'helmet', 'goggles', 'gloves', 'boots', 'apron',
    'mask', 'clipboard', 'notebook', 'blueprint', 'chart', 'map', 'syringe', 'monitor',
    'brave', 'patient', 'caring', 'stern', 'charismatic', 'humble', 'confident', 'cautious',
    'ambitious', 'competitive', 'cooperative', 'independent', 'assertive', 'empathetic', 'stoic',
    'disciplined', 'organized', 'reliable', 'punctual', 'trustworthy', 'honest', 'discreet',
    'calm', 'intense', 'focused', 'determined', 'persistent', 'tough',
    'leader', 'boss', 'mentor', 'apprentice', 'expert', 'novice', 'chief', 'senior',
    'junior', 'intern', 'volunteer', 'freelance', 'consultant', 'contractor', 'director', 'manager',
    'supervisor', 'specialist', 'assistant', 'founder', 'partner', 'colleague',
    'educated', 'self-taught', 'academic',
    'degree', 'certificate', 'apprenticeship', 'residency', 'training',
    'deadline', 'overtime', 'shift', 'seasonal', 'permanent', 'temporary', 'part-time', 'full-time',
    'on-call', 'nocturnal', 'structured', 'practical',
    'medical', 'legal', 'financial', 'educational', 'military', 'religious', 'scientific',
    'technological', 'agricultural', 'culinary', 'theatrical', 'journalistic', 'architectural',
    'engineering', 'commercial', 'governmental',
    'healing', 'teaching', 'building', 'designing', 'investigating', 'protecting', 'serving',
    'creating', 'repairing', 'inspecting', 'enforcing', 'advising', 'negotiating', 'rescuing',
    'defending', 'counseling', 'coaching', 'mentoring', 'guiding', 'leading', 'diagnosing',
    'treating', 'analyzing', 'researching', 'documenting', 'performing', 'entertaining', 'composing',
    'directing', 'producing', 'editing', 'publishing', 'welding', 'wiring', 'plumbing',
    'painting', 'sculpting', 'surveying', 'dangerous', 'safe', 'stressful', 'demanding',
    'grueling', 'rewarding', 'prestigious', 'powerful', 'influential',
    'essential', 'rare', 'elite', 'ethical', 'altruistic', 'principled',
    'uniformed', 'suited', 'robed', 'armored', 'sworn', 'elected', 'appointed', 'hired',
    'promoted', 'traditional', 'revolutionary', 'entrepreneurial',
    'corporate', 'nonprofit', 'salaried', 'hourly', 'commissioned',
    'monitoring', 'dispatching', 'responding', 'triaging', 'coding', 'debugging',
    'illustrating', 'animating', 'screenwriting', 'copywriting', 'translating', 'interpreting',
    'constructing', 'landscaping', 'roofing', 'harvesting', 'brewing', 'casting', 'polishing',
  ],

  activities: [
    'intense', 'relaxing', 'exhausting', 'effortless', 'grueling', 'gentle',
    'strenuous', 'leisurely', 'demanding', 'casual', 'extreme', 'challenging',
    'technical',
    'fast-paced', 'slow-paced', 'steady', 'explosive', 'continuous', 'intermittent',
    'punishing', 'forgiving', 'brutal', 'mellow', 'draining',
    'indoor', 'outdoor', 'underwater', 'aerial', 'mountain', 'beach', 'forest', 'urban',
    'rural', 'backyard', 'park', 'gym', 'studio', 'arena', 'court', 'field',
    'track', 'trail', 'road', 'river', 'lake', 'ocean', 'pool', 'rooftop',
    'garage', 'kitchen', 'garden', 'desert', 'cave', 'island', 'meadow',
    'solo', 'partner', 'team', 'group', 'family', 'friends', 'strangers',
    'competitive', 'cooperative', 'collaborative', 'individual', 'communal', 'social', 'private', 'public',
    'participant', 'leader', 'follower', 'coach', 'student', 'teacher',
    'mentor', 'amateur', 'professional', 'opponent', 'teammate', 'referee',
    'ball', 'bat', 'racket', 'paddle', 'club', 'stick', 'rod', 'pole',
    'net', 'goal', 'hoop', 'target', 'board', 'mat', 'rope', 'harness',
    'helmet', 'gloves', 'pads', 'shoes', 'boots', 'cleats', 'goggles', 'mask',
    'wheel', 'blade', 'sail', 'oar', 'pedal', 'handle', 'grip',
    'brush', 'needle', 'yarn', 'clay', 'paint', 'pencil', 'canvas',
    'whistle', 'stopwatch', 'scoreboard', 'flag', 'baton', 'disc', 'puck',
    'running', 'jumping', 'throwing', 'catching', 'kicking', 'hitting', 'swinging', 'spinning',
    'rolling', 'sliding', 'balancing', 'stretching', 'bending', 'twisting', 'lifting', 'pulling',
    'pushing', 'squeezing', 'gripping', 'aiming', 'launching', 'landing', 'falling',
    'flipping', 'tumbling', 'vaulting', 'hurdling', 'sprinting', 'jogging',
    'paddling', 'rowing', 'steering', 'braking', 'accelerating', 'gliding', 'floating',
    'ducking', 'dodging', 'weaving', 'lunging', 'pivoting', 'shuffling', 'skipping', 'hopping',
    'timed', 'scored', 'judged', 'measured', 'clocked', 'ranked',
    'choreographed', 'improvised', 'spontaneous', 'planned',
    'fast', 'slow', 'deliberate', 'precise', 'graceful', 'clumsy',
    'tempo', 'cadence', 'flow', 'momentum', 'pace', 'timing',
    'loud', 'quiet', 'silent', 'musical', 'peaceful', 'meditative', 'focused',
    'sweaty', 'breathless', 'exhilarating', 'calming', 'thrilling', 'exciting',
    'painful', 'refreshing', 'energizing', 'invigorating',
    'adrenaline', 'endorphin', 'zen', 'euphoric', 'drained',
    'sunny', 'rainy', 'snowy', 'windy', 'stormy', 'icy',
    'summer', 'winter', 'spring', 'autumn', 'seasonal', 'year-round',
    'tropical', 'arctic', 'temperate', 'humid', 'breezy',
    'daily', 'weekly', 'monthly', 'marathon', 'sprint',
    'lengthy', 'all-day', 'weekend', 'morning', 'evening',
    'dangerous', 'safe', 'risky', 'cautious', 'protected', 'supervised',
    'skilled', 'expert', 'novice', 'practiced', 'natural', 'trained',
    'disciplined', 'polished', 'raw', 'refined', 'creative',
    'colorful', 'detailed', 'traditional', 'modern', 'experimental', 'classical',
    'folk', 'freeform', 'structured', 'messy', 'clean',
    'dusty', 'wet', 'dry', 'muddy', 'sandy', 'grassy', 'therapeutic',
    'spiritual', 'cultural', 'educational', 'rewarding', 'satisfying',
    'hobby', 'sport', 'craft', 'art', 'game', 'exercise', 'practice', 'ritual',
    'tournament', 'match', 'race', 'performance', 'warmup', 'cooldown',
    'stretch', 'drill', 'final', 'overtime', 'uphill', 'downhill',
    'long-distance', 'relay', 'endurance', 'low-impact',
    'cardio', 'strength', 'flexibility', 'agility', 'balance', 'speed', 'power',
    'recovery', 'scoring', 'defending', 'passing', 'shooting',
    'sunrise', 'sunset', 'moonlit', 'nighttime', 'afternoon',
  ],

  movies: [
    'action', 'comedy', 'drama', 'horror', 'thriller', 'romance', 'mystery', 'fantasy',
    'western', 'musical', 'documentary', 'animated', 'noir', 'satire', 'parody', 'biopic',
    'heist', 'courtroom', 'disaster', 'espionage', 'gangster', 'slasher', 'zombie', 'vampire',
    'superhero', 'space', 'war', 'prison', 'sports', 'coming-of-age', 'road-trip', 'survival',
    'found-footage', 'whodunit', 'mockumentary', 'anthology',
    'suspenseful', 'heartwarming', 'terrifying', 'hilarious', 'tragic', 'uplifting', 'dark', 'lighthearted',
    'intense', 'relaxed', 'eerie', 'whimsical', 'gritty', 'polished', 'raw', 'dreamy',
    'melancholic', 'euphoric', 'tense', 'peaceful', 'chaotic', 'somber', 'playful', 'brooding',
    'nostalgic', 'futuristic', 'timeless', 'fresh', 'vibrant', 'muted',
    'chilling', 'sentimental', 'absurd', 'deadpan', 'campy', 'earnest', 'cynical',
    'hero', 'villain', 'sidekick', 'mentor', 'antihero', 'outlaw', 'detective',
    'spy', 'soldier', 'scientist', 'alien', 'robot', 'ghost', 'monster', 'wizard',
    'orphan', 'chosen-one', 'underdog', 'genius', 'fool', 'loner', 'leader', 'rebel',
    'partner', 'rival', 'traitor', 'savior', 'victim', 'survivor', 'witness', 'narrator',
    'assassin', 'fugitive', 'prisoner', 'king', 'peasant', 'con-artist', 'vigilante',
    'twist', 'cliffhanger', 'flashback', 'foreshadowing', 'montage', 'voiceover', 'prologue', 'epilogue',
    'betrayal', 'revenge', 'redemption', 'sacrifice', 'escape', 'chase', 'rescue', 'siege',
    'trial', 'duel', 'showdown', 'ambush', 'invasion', 'discovery', 'revelation', 'confession',
    'journey', 'quest', 'mission', 'investigation', 'conspiracy', 'prophecy', 'curse', 'transformation',
    'kidnapping', 'blackmail', 'framing', 'alibi', 'double-cross',
    'close-up', 'panoramic', 'aerial', 'underwater', 'slow-motion', 'time-lapse', 'tracking',
    'handheld', 'steady', 'shaky', 'smooth', 'zooming', 'panning',
    'colorful', 'black-and-white', 'neon', 'shadowy', 'sunlit', 'moonlit', 'candlelit',
    'blurry', 'sharp', 'grainy', 'saturated', 'desaturated', 'silhouetted',
    'orchestral', 'electronic', 'acoustic', 'silent', 'loud', 'whispered', 'echoing',
    'soundtrack', 'score', 'theme', 'ballad', 'anthem',
    'dialogue', 'monologue', 'scream', 'whisper', 'gunshot', 'explosion', 'siren', 'heartbeat',
    'choir', 'drums', 'strings', 'piano', 'guitar', 'silence',
    'medieval', 'Victorian', 'modern', 'colonial', 'wartime',
    'dystopian', 'utopian', 'post-apocalyptic', 'cyberpunk', 'steampunk', 'gothic', 'tropical', 'arctic',
    'urban', 'rural', 'suburban', 'wilderness', 'underground', 'orbital', 'otherworldly',
    'cold-war', 'frontier', 'ancient', 'samurai', 'viking',
    'blockbuster', 'indie', 'low-budget', 'high-budget', 'mainstream', 'arthouse', 'cult', 'experimental',
    'sequel', 'prequel', 'reboot', 'remake', 'spinoff', 'adaptation', 'original', 'franchise',
    'award-winning', 'controversial', 'acclaimed', 'banned', 'censored',
    'CGI', 'practical-effects', 'stop-motion', 'motion-capture', 'miniature', 'prosthetics',
    'classic', 'iconic', 'polarizing', 'beloved', 'hated', 'underrated', 'overrated',
    'groundbreaking', 'innovative', 'formulaic', 'predictable', 'surprising', 'shocking', 'boring',
    'emotional', 'intellectual', 'visceral', 'cerebral', 'entertaining', 'thought-provoking', 'escapist',
    'family-friendly', 'mature', 'graphic', 'tame', 'subtle', 'provocative', 'wholesome',
    'crying', 'laughing', 'screaming', 'cheering', 'gasping', 'cringing',
    'terrified', 'inspired', 'amazed', 'confused', 'satisfied', 'haunted', 'captivated', 'enchanted',
    'fast', 'slow', 'building', 'climactic', 'relentless', 'measured',
    'linear', 'nonlinear', 'fragmented', 'seamless', 'flowing',
    'sword', 'gun', 'car', 'spaceship', 'mask', 'cape', 'ring', 'map',
    'potion', 'bomb', 'shield', 'crown', 'throne', 'mirror', 'diary', 'letter',
    'treasure', 'artifact', 'weapon', 'vehicle', 'costume', 'disguise', 'gadget',
    'love', 'death', 'power', 'freedom', 'justice', 'identity', 'family', 'friendship',
    'forgiveness', 'obsession', 'madness', 'greed', 'honor', 'hope', 'despair', 'corruption',
    'innocence', 'destiny', 'fate', 'ambition', 'loyalty', 'isolation', 'belonging',
    'epic', 'intimate', 'sprawling', 'contained', 'lavish', 'sparse', 'beautiful',
    'stunning', 'elegant', 'clever', 'witty', 'dull', 'believable',
    'ridiculous', 'authentic', 'genuine', 'ensemble', 'cameo',
  ],

  emojis: [
    '😀', '😂', '🥹', '😍', '🤩', '😎', '🥳', '😤',
    '😱', '🤯', '😴', '🤮', '🥶', '🥵', '😈', '🤡',
    '👻', '💀', '👽', '🤖', '🎃', '👹', '💩', '🫠',
    '🫣', '🫡', '🤠', '🥸', '😇', '🤓', '🧐', '🤑',
    '👶', '👧', '👨', '👩', '👴', '👵', '🧑‍🎤', '🧑‍🚀',
    '🧑‍🍳', '🧑‍🔬', '🧑‍🎨', '🧑‍⚕️', '🦸', '🧟', '🧜', '🧚',
    '🧙', '🧝', '🤴', '👸', '💂', '🥷', '🧑‍🎄', '🧞',
    '👁️', '👀', '🧠', '👅', '💪', '🦵', '🦴', '❤️',
    '💔', '💯', '💢', '💤', '💬', '💭', '🕳️', '💣',
    '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼',
    '🐸', '🐵', '🐔', '🐧', '🐦', '🦅', '🦆', '🦉',
    '🦇', '🐺', '🐗', '🐴', '🦄', '🐝', '🐛', '🦋',
    '🐌', '🐞', '🐜', '🦂', '🐍', '🦎', '🐢', '🐙',
    '🦑', '🦀', '🐠', '🐬', '🐳', '🦈', '🐊', '🐘',
    '🦏', '🦛', '🐪', '🦒', '🦘', '🦬', '🐃', '🐄',
    '🐷', '🐑', '🐐', '🦌', '🐕', '🐈', '🦃', '🦚',
    '🦜', '🦩', '🐁', '🦔', '🐉', '🦕', '🦖', '🕷️',
    '🌸', '🌹', '🌻', '🌺', '🌷', '🌵', '🎄', '🌲',
    '🌴', '🍀', '🍁', '🍂', '🌾', '🪻', '🪸', '🍄',
    '🌍', '🌙', '⭐', '☀️', '🌈', '⛅', '❄️', '🔥',
    '💧', '🌊', '⚡', '🌪️', '🌋', '☄️', '💫', '🪐',
    '🍎', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐',
    '🍑', '🥝', '🍍', '🥥', '🥑', '🍆', '🥕', '🌽',
    '🌶️', '🥒', '🧄', '🧅', '🥔', '🍞', '🥐', '🧀',
    '🍖', '🍗', '🥩', '🌭', '🍔', '🍟', '🍕', '🌮',
    '🍣', '🍜', '🍝', '🍰', '🎂', '🧁', '🍩', '🍪',
    '🍫', '🍬', '🍭', '🍦', '☕', '🍵', '🧃', '🍺',
    '🍷', '🥂', '🍾', '🧊', '🥤', '🫖', '🥡', '🥢',
    '⚽', '🏀', '🏈', '⚾', '🎾', '🏐', '🏉', '🎱',
    '🏓', '🏸', '🏒', '🥊', '🎯', '⛳', '🎣', '🤿',
    '🎿', '🛷', '🏂', '🏋️', '🤸', '🧘', '🏄', '🚴',
    '🏇', '🤺', '⛷️', '🪂', '🏊', '🤽', '🧗', '🛹',
    '🚗', '🚕', '🚌', '🚑', '🚒', '🚁', '✈️', '🚀',
    '🛸', '🚢', '⛵', '🚂', '🚲', '🛵', '🏎️', '🚜',
    '🏠', '🏢', '🏰', '🏛️', '⛪', '🕌', '🗼', '🗽',
    '🎡', '🎢', '⛲', '🏖️', '🏔️', '🗻', '🏕️', '⛺',
    '🎸', '🎹', '🥁', '🎺', '🎻', '🪕', '🎤', '🎧',
    '🎬', '🎭', '🎨', '🖌️', '🎮', '🕹️', '🎲', '🧩',
    '♟️', '🎰', '🎳', '🃏', '📱', '💻', '⌨️', '🖥️',
    '🖨️', '📷', '📹', '🔭', '🔬', '💡', '🔦', '🕯️',
    '📚', '📖', '✏️', '🖊️', '📝', '📐', '📏', '✂️',
    '📎', '🔑', '🗝️', '🔒', '🔓', '🛡️', '⚔️', '🗡️',
    '🔫', '🪃', '🏹', '🪓', '🔧', '🔩', '⚙️', '🧲',
    '💎', '💰', '👑', '🏆', '🥇', '🥈', '🥉', '🎖️',
    '🎁', '🎈', '🎀', '🪅', '🎊', '🎉', '🧸', '🪆',
    '🪄', '🔮', '🧿', '🪬', '📯', '🚩', '🏴‍☠️', '🏳️‍🌈',
    '♻️', '⚠️', '🚫', '⛔', '❓', '❗', '✅', '❌',
  ],

};

class ClueDeck {
  constructor(listName) {
    this.listName = listName || 'animals';
    this.dealtThisStep = new Set();
    this.playedThisGame = new Set();
  }

  static getLists() {
    return Object.keys(CLUE_LISTS);
  }

  setList(listName) {
    if (CLUE_LISTS[listName]) {
      this.listName = listName;
      this.dealtThisStep.clear();
      this.playedThisGame.clear();
    }
  }

  startStep() {
    this.dealtThisStep.clear();
  }

  markPlayed(word) {
    this.playedThisGame.add(word);
  }

  draw(count) {
    const wordList = CLUE_LISTS[this.listName] || CLUE_LISTS.animals;
    const available = wordList.filter(w => !this.dealtThisStep.has(w) && !this.playedThisGame.has(w));

    if (available.length < count) {
      this.playedThisGame.clear();
      return this.draw(count);
    }

    const shuffled = [...available].sort(() => Math.random() - 0.5);
    const hand = shuffled.slice(0, count);
    hand.forEach(w => this.dealtThisStep.add(w));
    return hand;
  }

  resetRound() {
    this.dealtThisStep.clear();
    this.playedThisGame.clear();
  }
}

module.exports = ClueDeck;
